INSERT INTO MEMBER VALUES(MEM_SEQ.NEXTVAL,'admin','admin','admin','admin',null,0,0,0,0,null,sysdate,null);
INSERT INTO MEMBER VALUES(MEM_SEQ.NEXTVAL,'user','user','user','user',null,0,0,0,0,null,sysdate,null);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'1','1',1,'1','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'2','2',1,'2','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'3','3',1,'3','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',1,'4','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',1,'5','admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'1','1',2,'1','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'2','2',2,'2','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'3','3',2,'3','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',2,'4','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',2,'5','admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'1','1',3,'1','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'2','2',3,'2','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'3','3',3,'3','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',3,'4','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',3,'5','admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'1','1',4,'1','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'2','2',4,'2','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'3','3',4,'3','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',4,'4','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',4,'5','admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'1','1',5,'1','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'2','2',5,'2','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'3','3',5,'3','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',5,'4','admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',5,'5','admin',SYSDATE,NULL,NULL);
commit;